services:
  web:
    build: .
    container_name: laravel_web
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - biblioteka_db
    networks:
      - appnet

  biblioteka_db:
    image: mysql:latest
    container_name: laravel_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteka_atlas
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet


volumes:
  db_data:

networks:
  appnet:
    driver: bridge
